version: '3'

networks:
  frontend:

volumes:
  vol-gitlab-config:
  vol-gitlab-logs:
  vol-gitlab-data:

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: "${GITLAB_DOMAIN}"
    ports:
      - "1021:22"
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - vol-gitlab-config:/etc/gitlab
      - vol-gitlab-logs:/var/log/gitlab
      - vol-gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add gitlab.rb configuration here, each on its own line.
        # See: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
        external_url 'http://${GITLAB_DOMAIN}'
        letsencrypt['enable'] = false
        # Configure headers for outgoing email.
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'no-reply@${GITLAB_DOMAIN}'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab'
        gitlab_rails['gitlab_email_reply_to'] = 'no-reply@${GITLAB_DOMAIN}'
        # Send outgoing email via the SMTP container:
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_tls'] = false
        # Limit backup lifetime to 7 days (604800 seconds):
        gitlab_rails['backup_keep_time'] = 604800
